name: Continuous Integration PHP

on: [ pull_request ]

jobs:
  check-dependencies:
    strategy:
      matrix:
        php:
          - "8.2"
        dependencies:
          - ""
          - "--prefer-lowest"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype
          coverage: pcov

      - name: Install dependencies
        run: composer update --no-progress --no-interaction ${{ matrix.dependencies }}

      - name: Check Dependencies
        run: composer check-deps

  code-style:
    strategy:
      matrix:
        php:
          - "8.2"
        dependencies:
          - ""
          - "--prefer-lowest"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype

      - name: Install dependencies
        run: composer update --no-progress --no-interaction ${{ matrix.dependencies }}

      - name: Check Code Style
        run: composer cs-check

  phpstan:
    strategy:
      matrix:
        php:
          - "8.2"
        dependencies:
          - ""
          - "--prefer-lowest"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype

      - name: Install dependencies
        run: composer update --no-progress --no-interaction ${{ matrix.dependencies }}

      - name: PHPStan
        run: composer phpstan -- --no-progress

  psalm:
    strategy:
      matrix:
        php:
          - "8.2"
        dependencies:
          - ""
          - "--prefer-lowest"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype

      - name: Install dependencies
        run: composer update --no-progress --no-interaction ${{ matrix.dependencies }}

      - name: Psalm
        run: composer psalm

  phpunit:
    strategy:
      matrix:
        php:
          - "8.2"
        dependencies:
          - ""
          - "--prefer-lowest"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype
          coverage: pcov

      - name: Install dependencies
        run: composer update --no-progress --no-interaction ${{ matrix.dependencies }}

      - name: PHPUnit
        run: |
          vendor/bin/phpunit \
            --coverage-xml=build/coverage/coverage-xml \
            --log-junit=build/coverage/junit.xml \
            --coverage-clover=build/coverage/clover.xml

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-${{ matrix.php }}
          path: build/coverage/

  infection:
    strategy:
      matrix:
        php:
          - "8.2"
        dependencies:
          - ""
          - "--prefer-lowest"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype
          coverage: pcov

      - name: Install dependencies
        run: composer update --no-progress --no-interaction ${{ matrix.dependencies }}

      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage-${{ matrix.php }}
          path: build/coverage/

      - name: Infection coverage of changed lines
        if: "!contains(github.event.pull_request.labels.*.name, 'skip-infection')"
        run: |
          git fetch origin $GITHUB_BASE_REF $GITHUB_HEAD_REF
          vendor/bin/infection \
            --coverage=build/coverage \
            --git-diff-base=origin/$GITHUB_BASE_REF \
            --git-diff-lines \
            --logger-github \
            --min-msi=100 \
            --min-covered-msi=100 \
            --ignore-msi-with-no-mutations \
            -jmax

      - name: Save Infection result
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: infection-log-${{ matrix.php }}.txt
          path: infection-log.txt

  bc-breaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: ctype

      - name: Install dependencies
        run: composer update --no-progress --no-interaction

      - name: "Check for BC breaks"
        run: vendor/bin/roave-backward-compatibility-check







