name: Continuous Integration PHP

on: [ pull_request ]

jobs:
  qa:
    strategy:
      matrix:
        php:
          - "8.2"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype
          coverage: pcov

      - name: Prepare environment
        run: echo "COMPOSER_CACHE=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Composer Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.COMPOSER_CACHE }}
            vendor
          key: ${{ runner.os }}-composer

      - name: Install dependencies
        run: |
          composer update --no-progress --no-interaction > /dev/null

      - name: Check Dependencies
        run: composer check-deps

      - name: Check Code Style
        run: composer cs-check

      - name: PHPStan
        run: composer phpstan -- --no-progress

      - name: Psalm
        run: composer psalm

      - name: PHPUnit
        run: |
          vendor/bin/phpunit \
            --coverage-xml=build/coverage/coverage-xml \
            --log-junit=build/coverage/junit.xml \
            --coverage-clover=coverage.xml

      - name: Infection coverage of changed lines
        if: "!contains(github.event.pull_request.labels.*.name, 'skip-infection')"
        run: |
          git fetch origin $GITHUB_BASE_REF $GITHUB_HEAD_REF
          vendor/bin/infection \
            --coverage=build/coverage \
            --git-diff-base=origin/$GITHUB_BASE_REF \
            --git-diff-lines \
            --logger-github \
            --min-msi=100 \
            --min-covered-msi=100 \
            --ignore-msi-with-no-mutations \
            -jmax

      - name: "Check for BC breaks"
        run: vendor/bin/roave-backward-compatibility-check

      - name: Save Infection result
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: infection-log-${{ matrix.php }}.txt
          path: infection-log.txt
